set(mcuboot_KERNEL_HEX_NAME zephyr.hex)
set(mcuboot_ZEPHYR_BINARY_DIR /Users/justin/Github/FORKS/fota_v2/nrf/_build_asset_tracker_DK/mcuboot/zephyr)
set(mcuboot_KERNEL_ELF_NAME zephyr.elf)
list(APPEND mcuboot_BUILD_BYPRODUCTS /Users/justin/Github/FORKS/fota_v2/nrf/_build_asset_tracker_DK/mcuboot/zephyr/zephyr.hex)
list(APPEND mcuboot_BUILD_BYPRODUCTS /Users/justin/Github/FORKS/fota_v2/nrf/_build_asset_tracker_DK/mcuboot/zephyr/zephyr.elf)
